/*****************************************************************************
* Model: Jigbox.qm
* File:  ../../firmware/qm_code/accelerometerListener.h
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#include "jigbox.h"
#include "qp_port.h"

extern QActive* AO_AccelerometerListener;
