/*****************************************************************************
* Model: Jigbox.qm
* File:  ../../firmware/qm_code/accelerometerListener.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#include "accelerometerListener.h"

/* $(AOs::AccelerometerListener) ...........................................*/
typedef struct AccelerometerListenerTag {
/* protected: */
    QActive super;

/* public: */
    uint8_t[100] history;

/* protected: */
    QTimeEvt timeEvt;
} AccelerometerListener;

/* public: */
void AccelerometerListener_ctor(AccelerometerListener *me);

/* protected: */
QState AccelerometerListener_initial(AccelerometerListener *me, QEvent const *e);
QState AccelerometerListener_state1(AccelerometerListener *me, QEvent const *e);


static Display l_Listener;    // the singleton AccelerometerListener

/* Global objects ----------------------------------------------------------*/
QActive * const AO_AccelerometerListener = (QActive *)&l_Listener; /* the opaque pointer */

/* $(AOs::AccelerometerListener) ...........................................*/
/* $(AOs::AccelerometerListener::ctor) .....................................*/
void AccelerometerListener_ctor(AccelerometerListener *me) {
}
/* $(AOs::AccelerometerListener::Statechart) ...............................*/
/* @(/2/2/3/0) */
QState AccelerometerListener_initial(AccelerometerListener *me, QEvent const *e) {
    QTimeEvt_postEvery(&me->timeEvt,(QActive*)me, 1);

    return Q_TRAN(&AccelerometerListener_state1);
}
/* $(AOs::AccelerometerListener::Statechart::state1) .......................*/
QState AccelerometerListener_state1(AccelerometerListener *me, QEvent const *e) {
    switch (e->sig) {
    }
    return Q_SUPER(&QHsm_top);
}

