/*****************************************************************************
* Model: Jigbox.qm
* File:  ../../firmware/qm_code/audioPlayer.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
/* $(Events::EV_NOTE_DONE) .................................................*/


/* $(Events::EV_START_NOTE) ................................................*/

/* $(AOs::AudioPlayer) .....................................................*/
Note[6] AudioPlayer_channels;
/* $(AOs::AudioPlayer::startPlaying) .......................................*/
bool AudioPlayer_startPlaying(AudioPlayer *me) {
}
/* $(AOs::AudioPlayer::Statechart) .........................................*/
/* @(/2/0/4/0) */
QState AudioPlayer_initial(AudioPlayer *me, QEvent const *e) {
    QTimeEvt_postEvery(&me->timeEvt,(QActive*)me,TICKS_PER_SEC / 2);

    return Q_TRAN(&AudioPlayer_idle);
}
/* $(AOs::AudioPlayer::Statechart::idle) ...................................*/
QState AudioPlayer_idle(AudioPlayer *me, QEvent const *e) {
    switch (e->sig) {
        /* @(/2/0/4/1) */
        case Q_ENTRY_SIG: {
            audioOff();
            activeNotes = 0;
            return Q_HANDLED();
        }
        /* @(/2/0/4/1/0) */
        case EV_START_NOTE_SIG: {
            startPlaying(e->note);
            activeNotes++;
            return Q_TRAN(&AudioPlayer_playing);
        }
    }
    return Q_SUPER(&QHsm_top);
}
/* $(AOs::AudioPlayer::Statechart::playing) ................................*/
QState AudioPlayer_playing(AudioPlayer *me, QEvent const *e) {
    switch (e->sig) {
        /* @(/2/0/4/2/0) */
        case EV_NOTE_DONE_SIG: {
            activeNotes--;
            return Q_TRAN(&AudioPlayer_idle);
        }
    }
    return Q_SUPER(&QHsm_top);
}

