/*****************************************************************************
* Model: Jigbox.qm
* File:  ../../firmware/qm_code/buttonWatcher.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#include "buttonWatcher.h"

/* $(AOs::ButtonWatcher) ...................................................*/
/* $(AOs::ButtonWatcher::lightLED) .........................................*/
void ButtonWatcher_lightLED(ButtonWatcher *me) {
}
/* $(AOs::ButtonWatcher::ledsOff) ..........................................*/
void ButtonWatcher_ledsOff(ButtonWatcher *me) {
}
/* $(AOs::ButtonWatcher::Statechart) .......................................*/
/* @(/2/3/2/0) */
QState ButtonWatcher_initial(ButtonWatcher *me, QEvent const *e) {
    return Q_TRAN(&ButtonWatcher_idle);
}
/* $(AOs::ButtonWatcher::Statechart::idle) .................................*/
QState ButtonWatcher_idle(ButtonWatcher *me, QEvent const *e) {
    switch (e->sig) {
        /* @(/2/3/2/1) */
        case Q_ENTRY_SIG: {
            ledsOff();
            return Q_HANDLED();
        }
        /* @(/2/3/2/1/0) */
        case EV_BUTTON_PRESSED_SIG: {
            return Q_TRAN(&ButtonWatcher_pressed);
        }
    }
    return Q_SUPER(&QHsm_top);
}
/* $(AOs::ButtonWatcher::Statechart::pressed) ..............................*/
QState ButtonWatcher_pressed(ButtonWatcher *me, QEvent const *e) {
    switch (e->sig) {
        /* @(/2/3/2/2) */
        case Q_ENTRY_SIG: {
            lightLED();
            return Q_HANDLED();
        }
        /* @(/2/3/2/2/0) */
        case EV_BUTTON_RELEASED_SIG: {
            return Q_TRAN(&ButtonWatcher_idle);
        }
    }
    return Q_SUPER(&QHsm_top);
}


