/*****************************************************************************
* Model: Jigbox.qm
* File:  ../../firmware/qm_code/main.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/

