QP/C: QSubscrList Struct Reference
QSubscrList Struct Reference
Subscriber-List structure.
#include <qf.h>
Data Fields
uint8_t bits [((63-1)/8)+1]
Detailed Description
Subscriber-List structure.
This data type represents a set of active objects that subscribe to a given signal. The set is represented as an array of bits, where each bit corresponds to the unique priority of an active object.
See also:
::QSubscrListTag for the description of the data members
Definition at line 605 of file qf.h.
Field Documentation
uint8_t QSubscrList::bits[((63-1)/8)+1]
An array of bits representing subscriber active objects. Each bit in the array corresponds to the unique priority of the active object. The size of the array is determined of the maximum number of active objects in the application configured by the #QF_MAX_ACTIVE macro. For example, an active object of priority p is a subscriber if the following is true: ((bits[QF_div8Lkup[p]] & QF_pwr2Lkup[p]) != 0)
See also:
QF_psInit(), QF_div8Lkup, QF_pwr2Lkup, #QF_MAX_ACTIVE
Definition at line 616 of file qf.h.
Referenced by QActive_subscribe(), QActive_unsubscribe(), QActive_unsubscribeAll(), and QF_publish().
The documentation for this struct was generated from the following file:
qf.h