@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"C:\tools\IAR\ARM_KS_6.10\common\bin\cspybat" "C:\tools\IAR\ARM_KS_6.10\arm\bin\armproc.dll" "C:\tools\IAR\ARM_KS_6.10\arm\bin\armlmiftdi.dll"  %1 --plugin "C:\tools\IAR\ARM_KS_6.10\arm\bin\armbat.dll" --flash_loader "C:\tools\IAR\ARM_KS_6.10\arm\config\flashloader\TexasInstruments\FlashLM3S8xx.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "C:\tools\IAR\ARM_KS_6.10\arm\CONFIG\debugger\TexasInstruments\iolm3s811.ddf" "--drv_verify_download" "--semihosting" "--device=LM3S811" "--lmiftdi_speed=500" 


